### ISSUE TITLE
0.20.0a66 Crashes

### ISSUE THREAD

**Issue by galuel** [duniter/duniter#460]
Launching Duniter 0.20.0a66 this morning, windows don't respond (only log window opens) and then after some seconds it crashes... Log file : [duniter.log.zip](https://github.com/duniter/duniter/files/288251/duniter.log.zip)

**Comment by c-geek** [comment]
OK I see errors that were fixed in latest releases, please update to [alpha81 version](https://github.com/duniter/duniter/releases/tag/v0.20.0a81).

Also, the logs UI may make the application crash, indeed. Improvements has to be made on this.

**Comment by galuel** [comment]
Ok, now it works ! But it wasn't working only by installing the new version, there was still crashes. So I manually deleted entirely the ~/.config/duniter folder, then reinstalling the new version, entered again my key (why the "salt" = first password, is viewable !? It should not be, I entered a password here, I don't want it to be seen...), and then he made a full synchronisation.

**Comment by c-geek** [comment]
Created #498 for this "salt" issue.
